<img src="img/salon.jpg" height="500" width="765"/>
<p>
    Những dịch vụ này được chàng trai Nguyễn Xuân Lộc (21 tuổi) mang đến tận nhà khách hàng để làm hài lòng các "boss" (sếp - PV) - cách gọi vui mà những người yêu thú cưng dành cho các "bé" chó, mèo.
    <br><b>Nghề lắm công phu</b><br>
    Đã có rất nhiều dịch vụ spa cho thú cưng, nhưng Lộc nằm trong số ít những người đến tận nhà làm, thay vì yêu cầu khách mang chó, mèo đến tiệm. Quyết định lựa chọn mô hình này xuất phát từ mong muốn mang đến cho khách sự thuận lợi và thoải mái, nhưng cũng đồng nghĩa với việc nhận phần khó về mình.
    Tại cửa hàng, nhân viên spa có đủ dụng cụ để thao tác, chủ được yêu cầu ngồi chờ bên ngoài để tránh việc thú cưng thấy chủ sẽ nhõng nhẽo, không nghe lời, thậm chí trở nên hung dữ. Trong khi đó, dịch vụ tại nhà đòi hỏi Lộc cùng nhân viên nhanh chóng làm quen với mỗi căn nhà mình đến, từ phòng tắm, hệ thống nước, đến việc thao tác với những dụng cụ nhất định, không đầy đủ như tại cửa hàng.
    "Những khó khăn này đều giúp tôi trở nên linh hoạt hơn, tích lũy kinh nghiệm trong việc chăm sóc thú tại nhà. Để chuẩn bị chu đáo, tôi thường hỏi nhu cầu của khách, giảm thiểu những thiếu sót trong quá trình thực hiện" - Lộc cho biết.
    Các dụng cụ cần chuẩn bị để chăm sóc các "boss" bao gồm máy sấy, tông đơ, kéo, đồ mài móng, thuốc vệ sinh tai, mắt, răng miệng… hầu hết có thể mang đến nhà khách hàng. Riêng khâu cắt tạo kiểu, Lộc nhận định làm tại cửa hàng sẽ thuận tiện hơn. Spa cho thú cưng là một nghề lắm "công phu" bởi không chỉ tìm hiểu nhu cầu của khách mà còn cần nắm rõ về từng giống chó, tình trạng lông và quan trọng nhất là làm quen với chó, mèo để tránh bị… cắn.
    "Đối với những trường hợp không thể làm được như chó mèo khó làm quen hoặc đang mắc bệnh, chúng tôi buộc phải từ chối" - Lộc giải thích.<br>
    Trong toàn bộ quá trình, cắt tỉa được xem là một trong những khâu quan trọng nhất, đòi hỏi người thợ phải có tay nghề. Từng giống chó có những kiểu cắt tỉa đặc trưng, ví dụ như giống chó poodle phải được cắt lông tròn đều hai bên đầu sao cho cân xứng. "Vì vậy thợ cắt tỉa rất tập trung và kiên nhẫn. Điều tiên quyết của thợ lành nghề là quen với dụng cụ, đặc biệt là kéo, để cắt theo đúng ý họ" - Lộc nhấn mạnh.
    Việc gặp phải rắc rối trong công việc cũng không hiếm với những bạn trẻ này. Dù đã trao đổi trước với chủ để đảm bảo thú cưng được chích ngừa, nhưng Lộc và các nhân viên cũng chuẩn bị tinh thần bị các "bé" chó, mèo phản ứng như cắn, cào. Nhìn chung, loài chó dễ hợp tác hơn so với mèo vì chúng thân thiện và không sợ nước. Với trường hợp khách chưa hài lòng, ngoài việc xin lỗi, Lộc và đồng nghiệp phải đưa ra phương án giải quyết.
    <br><b>Tình yêu với thú cưng</b><br>
    "Tôi nuôi một chú chó bull Pháp được 2 năm nay và bắt đầu tìm hiểu về những dịch vụ chăm sóc thú cưng để phục vụ cho những người yêu động vật" - Lộc nói. Trong nhiều tháng, anh xem các trang web, Instagram để học cách cắt, tỉa lông chó, hay kỹ năng spa cho chó, mèo tại nhà.
    Mỗi lần chăm sóc cho "boss", chàng trai 21 tuổi lại "bỏ túi" thêm những câu chuyện thú vị về những người bạn bốn chân. Có "boss" cực kỳ đáng yêu và chịu hợp tác, giúp người làm dịch vụ không mất quá nhiều công sức. Ngược lại, có ca "khó nhằn" khiến Lộc và mọi người phải mất hơn nửa ngày chỉ để làm quen và cạo lông.
    Đi qua mùa dịch Covid-19, những người trẻ yêu nghề như Lộc và các nhân viên vẫn miệt mài đến nhà khách hàng để làm nghề khá đặc biệt này. Để đảm bảo sức khỏe, Lộc cùng đồng nghiệp luôn trang bị đầy đủ khẩu trang, găng tay, xịt khử khuẩn khi tiếp xúc với khách.
    "Đôi lúc thật sự vất vả, chúng tôi đi làm mà quên cả giờ ăn. Bù lại, được khách tin tưởng giao thú cưng cho mình chăm sóc, có người đến từ nơi rất xa, rồi một số bạn trẻ xin học nghề, đó là động lực để tôi tiếp tục theo đuổi công việc mình đã chọn" - Lộc cười hạnh phúc.
</p>